before_script:
- apt-get update -yqq > /dev/null
- apt-get install -yqq --no-install-recommends git libicu-dev zlib1g-dev libxml2-dev > /dev/null
- docker-php-ext-install zip > /dev/null
- curl -sS https://getcomposer.org/installer | php
- mv composer.phar /usr/local/bin/composer
- composer self-update
- composer install --no-suggest --no-progress --prefer-dist

test:5.5:
  image: php:5.5
  script:
  - vendor/bin/phpunit
  - ./sniff.sh

test:5.6:
  image: php:5.6
  script:
  - vendor/bin/phpunit
  - ./sniff.sh

test:7.0:
  image: php:7.0
  script:
  - vendor/bin/phpunit
  - ./sniff.sh

test:7.1:
  image: php:7.1
  script:
  - vendor/bin/phpunit
  - ./sniff.sh

test:7.2:
  image: php:7.2
  script:
  - vendor/bin/phpunit
  - ./sniff.sh
